-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 05-Dez-2019 às 03:39
-- Versão do servidor: 10.4.8-MariaDB
-- versão do PHP: 7.1.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `celke`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `jogos`
--

CREATE TABLE `jogos` (
  `id` int(10) NOT NULL,
  `nome_J` varchar(150) NOT NULL,
  `categoria` varchar(150) NOT NULL,
  `descri` text NOT NULL,
  `plataforma` text NOT NULL,
  `preco` varchar(30) NOT NULL,
  `link_J` varchar(500) NOT NULL,
  `img_1` varchar(100) NOT NULL,
  `img_2` varchar(150) NOT NULL,
  `img_3` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `jogos`
--

INSERT INTO `jogos` (`id`, `nome_J`, `categoria`, `descri`, `plataforma`, `preco`, `link_J`, `img_1`, `img_2`, `img_3`) VALUES
(2, 'Assassin\'s Creed Black Flag', 'Ação', 'O ano é 1715. Os piratas governam o Caribe e estabeleceram sua própria república sem lei, onde corrupção, ganância e crueldade são comuns.   Entre esses bandidos é um jovem capitão impetuoso chamado Edward Kenway. Sua luta pela glória lhe valeu o respeito de lendas como Barba Negra, mas também o atraiu para a antiga guerra entre Assassinos e Templários, uma guerra que pode destruir tudo o que os piratas construíram.   Bem-vindo à Era de Ouro da Pirataria.', 'Mínimos SO: Windows Vista SP2 ou Windows 7 SP1 ou Windows 8 (versões 32/64 bits) Processador: Intel Core2Quad Q8400 @ 2.6 GHz or AMD Athlon II X4 620 @ 2.6 GHz Memória: 2 GB de RAM Placa de vídeo: Nvidia Geforce GTX 260 ou AMD Radeon HD 4870 (512MB VRAM com shader Model 4.0 ou superior) Armazenamento: 30 GB de espaço disponível Placa de som: placa de som compatível com DirectX com drivers mais recentes Outras observações: Windows-Compatible keyboard and mouse required, controller optional.  RECOMENDADOS: SO: Windows Vista SP2 ou Windows 7 SP1 ou Windows 8 (versões 32/64 bits) Processador: Intel Core i5 2400S a 2,5 GHz ou superior ou AMD Phenom II x4 940 a 3,0 GHz Memória: 4 GB de RAM Placa de vídeo: Nvidia GeForce GTX 470 ou AMD Radeon HD 5850 (1024MB VRAM com Shader Model 5.0) ou superior Armazenamento: 30 GB de espaço disponível Placa de som: placa de som compatível com DirectX com drivers mais recentes Outras partes: Placas de vídeo compatíveis no momento do lançamento: Nvidia GeForce GTX 260', 'R$59.99', 'https://store.steampowered.com/app/242050/Assassins_Creed_IV_Black_Flag/', '5de84db4e5f6b.jpg', '5de84db4e5f81.jpg', '5de84db4e5f8f.jpg'),
(3, 'Counter-Strike: Global Offensive (CS: GO)', 'Ação', 'Counter-Strike: Global Offensive (CS: GO) expandirá na jogabilidade de ação baseada em equipes na qual foi pioneiro quando foi lançado há 12 anos. CS: GO contém novos mapas, personagens e armas, além de conter versões atualizadas de conteúdos do CS clássico (como de_dust2). Além disso, CS: GO introduzirá novos modos de jogo, criação de partidas (matchmaking), placares de líderes e mais. \"Counter-Strike surpreendeu a indústria de jogos quando o improvável MOD virou o jogo de ação online para PC mais jogado no mundo quase imediatamente após seu lançamento em agosto de 1999,\" disse Doug Lombardi na Valve. \"Pelos últimos 12 anos, ele continuou sendo um dos jogos mais jogados no mundo, manteve destaque em torneios competitivos de jogos e a franquia vendeu mais de 26 milhões de cópias no mundo todo. CS: GO promete expandir na jogabilidade premiada de CS\' e permitir seu acesso por jogadores não só no PC, mas também em consoles de última geração e no Mac.\"', 'MÍNIMOS: SO: Windows® 7/Vista/XP Processador: Intel® Core™ 2 Duo E6600 or AMD Phenom™ X3 8750 processor or better Memória: 2 GB de RAM Placa de vídeo: Video card must be 256 MB or more and should be a DirectX 9-compatible with support for Pixel Shader 3.0 DirectX: Versão 9.0c Armazenamento: 15 GB de espaço disponível', 'Gratis', 'https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/', '5de84e103f688.jpg', '5de84e103f69b.jpg', '5de84e103f6ac.jpg'),
(4, 'Euro Truck Simulator 2', 'Esportes', 'iaje pela Europa como o rei da estrada, um caminhoneiro que entrega cargas importantes em distâncias impressionantes! Com dezenas de cidades para explorar a partir do Reino Unido, Bélgica, Alemanha, Itália, Holanda, Polônia e muitas outras, sua resistência, habilidade e velocidade serão levadas aos seus limites. Se você tem o que é preciso para fazer parte de uma força de caminhões de elite, chegue ao volante e prove!', 'MÍNIMO: OS: Windows 7 Processador: Dual core CPU 2.4 GHz Memória: 4 GB de RAM Gráficos: GeForce GTS 450-class (Intel HD 4000) Disco Rígido: 3 GB de espaço disponível  RECOMENDADO: OS: Windows 7/8.1/10 64-bit Processador: CPU quad core de 3,0 GHz Memória: 6 GB de RAM Gráficos: GeForce GTX 760-class (2 GB) Disco Rígido: 3 GB de espaço disponível', 'R$ 39,99 ', 'https://store.steampowered.com/app/227300/Euro_Truck_Simulator_2/', '5de84f9427aee.jpg', '5de84f9427afc.jpg', '5de84f9427b03.jpg'),
(5, 'Fallout 4', 'Indie', 'Bethesda Game Studios, the award-winning creators of Fallout 3 and The Elder Scrolls V: Skyrim, welcome you to the world of Fallout 4 – their most ambitious game ever, and the next generation of open-world gaming. As the sole survivor of Vault 111, you enter a world destroyed by nuclear war. Every second is a fight for survival, and every choice is yours. Only you can rebuild and determine the fate of the Wasteland. Welcome home.', 'MÍNIMOS: Requer um processador e sistema operacional de 64 bits SO: Windows 7/8/10 (64-bit OS required) Processador: Intel Core i5-2300 2.8 GHz/AMD Phenom II X4 945 3.0 GHz or equivalent Memória: 8 GB de RAM Placa de vídeo: NVIDIA GTX 550 Ti 2GB/AMD Radeon HD 7870 2GB or equivalent Armazenamento: 30 GB de espaço disponível  RECOMENDADOS: Requer um processador e sistema operacional de 64 bits SO: Windows 7/8/10 (64-bit OS required) Processador: Intel Core i7 4790 3.6 GHz/AMD FX-9590 4.7 GHz or equivalent Memória: 8 GB de RAM Placa de vídeo: NVIDIA GTX 780 3GB/AMD Radeon R9 290X 4GB or equivalent Armazenamento: 30 GB de espaço disponível', 'R$ 69,99 ', 'https://store.steampowered.com/agecheck/app/377160/', '5de85019bbd90.jpg', '5de85019bbd9d.jpg', '5de85019bbda4.jpg'),
(6, 'FORTNITE', 'Batle Royale', 'O Battle Royale do Fortnite é o nosso modo JxJ GRATUITO com 100 jogadores. Um mapa gigante. Um ônibus de batalha. As habilidades de construção e os ambientes destrutíveis do Fortnite combinados com intenso combate JxJ. O último sobrevivente vence. Disponível em PC, PlayStation®4, Xbox One, Nintendo Switch, Android, iOS e Mac.', 'MÍNIMOS: Placa de vídeo Intel HD 4000 Processador Core i3 2.4 Ghz Memória RAM de 4 GB RAM Sistema operacional Windows 7/8/10 64-bit + Mac OSX Sierra  RECOMENDADOS: Placa de vídeo Nvidia GTX 660 ou AMD Radeon HD 7870 compatível com DirectX 11 GPU Memória de vídeo de 2 GB VRAM Processador Core i5 2.8 Ghz Memória RAM de 8 GB RAM Sistema operacional Windows 7/8/10 64-bit', 'Gratis', 'https://www.epicgames.com/fortnite/pt-BR/home', '5de850743fcb4.jpg', '5de850743fcc0.jpg', '5de850743fcc8.jpg'),
(7, 'GOD OF WAR', 'Ação', 'Um novo começo ousado: sua vingança contra os deuses do Olimpo agora é passado e Kratos vive como um homem comum no reino dos monstros e deuses nórdicos. E é nesse mundo inóspito e implacável que ele precisa lutar para sobreviver... e ensinar seu filho a fazer o mesmo. Essa nova versão surpreendente de God of War desconstrói os principais elementos que definiram a série (combates gratificantes, proporção espetacular e uma narrativa poderosa), combinando-os de uma forma diferente. • Uma segunda oportunidade: Kratos é pai novamente. Assumindo o papel de mentor e protetor de seu filho, Atreus, que está determinado a conquistar seu respeito, Kratos é forçado a lidar e controlar a fúria que, por muito tempo, foi sua essência, e a explorar um mundo extremamente perigoso com seu filho. • Um mundo mais sombrio e elementar: desde as colunas de mármore de ornamentação do Olimpo até as florestas, montanhas e cavernas realistas do universo nórdico pré-viking, esse é um reino claramente novo com seu próprio panteão de criaturas, monstros e deuses. Com uma nova ênfase na descoberta e na exploração, esse mundo atrairá os jogadores para explorar cada centímetro do cenário surpreendentemente ameaçador de God of War, que é, sem dúvida, o maior da série. • Combates físicos violentos: com uma câmera livre e por cima do corpo que aproxima ainda mais o jogador da ação, as lutas de God of War refletem o panteão de criaturas nórdicas que Kratos enfrentará: grandiosas, realistas e exaustivas. Uma nova arma principal e novas habilidades mantêm o espírito que define God of War, além de apresentarem uma visão de conflitos violentos que criam uma nova base para o gênero. Software sujeito à licença e à garantia limitada (us.playstation.com/softwarelicense/br). É preciso ter uma conta para usar os recursos online, que estão sujeitos aos termos de serviço e à política de privacidade aplicável (playstationnetwork.com/terms-of-service e playstationnetwork.com/privacy-policy). A taxa única de licença dá o direito de jogar no sistema PS4™ principal designado e outros sistemas PS4™ quando está usando essa conta.', 'PS4', 'R$79,90', 'https://store.playstation.com/pt-br/product/UP9000-CUSA07408_00-00000000GODOFWAR', '5de850b83a735.jpg', '5de850b83a741.jpg', '5de850b83a748.jpg'),
(8, 'Grand Theft Auto V', 'Ação', 'Junte-se ao lendário empresário Tony Prince para inaugurar uma boate de alto nível ao som da batida alucinante dos renomados DJs Solomun, Tale Of Us, Dixon e Black Madonna. Use-a como fachada para a maior rede de esquemas criminais em San Andreas. Quando um malandro de rua, um ladrão de bancos aposentado e um psicopata aterrorizante se envolvem com alguns dos criminosos mais assustadores e loucos do submundo, o governo dos EUA e a indústria do entretenimento, eles devem realizar golpes ousados para sobreviver nessa cidade implacável onde não podem confiar em ninguém, nem mesmo um no outro. Grand Theft Auto V para PC oferece aos jogadores a opção de explorar o gigantesco e premiado mundo de Los Santos e Blaine County em resoluções de até 4K e além, assim como a chance de experimentar o jogo rodando a 60 FPS (quadros por segundo). O jogo oferece uma ampla seleção de opções de personalização específicas para o PC, com mais de 25 configurações separadas para qualidade de textura, sombreamentos, suavização de bordas e muito mais. Além disso, ele contém diversas opções de personalização dos controles de mouse e teclado. Entre as opções adicionais estão a densidade da população, o controle do tráfego de carros e pedestres, suporte para dois ou três monitores, compatibilidade com telas 3D e suporte para controle plug-and-play. Grand Theft Auto V para PC inclui o Grand Theft Auto Online, com suporte para até 30 jogadores e dois espectadores. Grand Theft Auto Online para PC inclui todas as atualizações de jogo e conteúdos criados pela Rockstar lançados desde que Grand Theft Auto Online foi ao ar, incluindo os recém-lançados Golpes e Modos Adversários. A versão para PC do Grand Theft Auto V e Grand Theft Auto Online apresenta o Modo em Primeira Pessoa, que dá aos jogadores a chance de explorar o mundo incrivelmente detalhado de Los Santos e Blaine County de uma maneira completamente nova.', 'Mínimo:Requer um processador e sistema operacional de 64 bits SO: Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1 Processador: Intel Core 2 Quad CPU Q6600 @ 2.40 GHz (4 CPUs) / AMD Phenom 9850 Quad-Core (4 CPUs) @ 2.5 GHz Memória: 4 GB de RAM Placa de vídeo: NVIDIA 9800 GT 1 GB / AMD HD 4870 1 GB (DX 10, 10.1, 11) Armazenamento: 72 GB de espaço disponível Placa de som: 100% compatível com DirectX 10', 'R$ 69,99', 'https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/', '5de8511f81880.jpg', '5de8511f8188f.jpg', '5de8511f8189a.jpg'),
(9, 'Halo 4', 'Indie', 'Halo 4 é um jogo eletrônico de tiro em primeira pessoa desenvolvido pela 343 Industries e publicado pela Microsoft Studios exclusivamente para o Xbox 360. Halo 4 é o primeiro de uma nova trilogia de jogos da série Halo, nomeada de \"trilogia Reclaimer\".', 'X BOX One', 'R$ 89.99', 'https://www.microsoft.com/pt-br/p/halo-4/c26xnflhtsgh?activetab=pivot:overviewtab', '5de851982e2a2.jpg', '5de851982e2b0.jpg', '5de851982e2b6.jpg'),
(10, 'Just Cause 4', 'Ação', 'Conheça Solís, um imenso território na América do Sul repleto de conflito, opressão e condições climáticas extremas. Just Cause 4 mostra o agente Rico Rodriguez chegando em Solís para buscar a verdade sobre o passado dele, custe o que custar. Equipe o traje planador e o gancho totalmente personalizável e prepare-se para entrar no olho do furacão!', 'MÍNIMOS: SO: Windows 7 SP1 with Platform Update for Windows 7 (64-bit versions only) Processador: Intel Core i5-2400 @ 3.1 GHz | AMD FX-6300 @ 3.5 GHz or better Memória: 8 GB de RAM Placa de vídeo: NVIDIA GeForce GTX 760 (2GB VRAM or better) | AMD R9 270 (2GB VRAM or better) DirectX: Versão 11 Armazenamento: 59 GB de espaço disponível  RECOMENDADOS: SO: Windows 10 (64-bit versions only) Processador: Intel Core i7-4770 @ 3.4 GHz | AMD Ryzen 5 1600 @ 3.2 GHz or equivalent Memória: 16 GB de RAM Placa de vídeo: NVIDIA GeForce GTX 1070 (6GB VRAM or better) | AMD Vega 56 (6GB VRAM or better) DirectX: Versão 11 Armazenamento: 59 GB de espaço disponível', 'R$ 156,72', 'https://store.steampowered.com/app/517630/Just_Cause_4/', '5de851e03e3c9.jpg', '5de851e03e3e4.jpg', '5de851e03e3f0.jpg'),
(11, 'Mortal Kombat 11', 'Ação', 'Mortal Kombat está de volta, melhor do que nunca, em uma evolução da icônica franquia. A Edição Standard de Mortal Kombat 11 inclui: • Jogo Principal Todas as variações de customização de personagens lhe dão liberdade total para personalizar os lutadores e torná-los únicos. Sinta-se mais perto da luta com os crânios rachados e olhos saltados dos novos gráficos. Com lutadores klássicos, novos e antigos, a incrível cinemática do modo história de Mortal Kombat continua a contar a saga épica de 25 anos atrás.', 'MÍNIMOS: SO: 64-bit Windows 7 / Windows 10 Processador: Intel Core i5-750, 2.66 GHz / AMD Phenom II X4 965, 3.4 GHz or AMD Ryzen™ 3 1200, 3.1 GHz Memória: 8 GB de RAM Placa de vídeo: NVIDIA® GeForce™ GTX 670 or NVIDIA® GeForce™ GTX 1050 / AMD® Radeon™ HD 7950 or AMD® Radeon™ R9 270 DirectX: Versão 11 Rede: Conexão de internet banda larga  RECOMENDADOS: SO: 64-bit Windows 7 / Windows 10 Processador: Intel Core i5-2300, 2.8 GHz / AMD FX-6300, 3.5GHz or AMD Ryzen™ 5 1400, 3.2 GHz Memória: 8 GB de RAM Placa de vídeo: NVIDIA® GeForce™ GTX 780 or NVIDIA® GeForce™ GTX 1060-6GB / AMD® Radeon™ R9 290 or RX 570 DirectX: Versão 11 Rede: Conexão de internet banda larga', 'R$ 199,99 ', 'https://store.steampowered.com/app/976310/Mortal_Kombat11/', '5de852577b579.png', '5de852577b588.png', '5de852577b591.png'),
(12, 'Need for Speed ​​Hot Pursuit', 'Esportes', 'Need for Speed ​​Hot Pursuit lança você em uma nova paisagem de mundo aberto ao volante dos carros mais rápidos e bonitos do mundo. De Criterion, o estúdio premiado por trás da série Burnout, Hot Pursuit irá redefinir jogos de corrida para toda uma nova geração. Você experimentará velocidades impressionantes, quedas e escapadas ao enfrentar seus amigos no jogo Need for Speed ​​mais conectado de todos os tempos. Por meio do Need for Speed ​​Autolog e sua abordagem inovadora à concorrência social conectada, sua experiência Hot Pursuit se estenderá além do console para a Web, movendo constantemente seu jogo em direções novas e exclusivas. Carregado com ação, este jogo irá desafiá-lo a se tornar o melhor policial do Condado de Seacrest ou o mais procurado. Pela primeira vez em um jogo Need for Speed, você poderá jogar uma carreira completa em ambos os lados da lei. Se você é um velocista de chumbo ou um policial com uma média, certifique-se de que seus aviadores são impecáveis ​​e seu registro de condução é tudo menos isso.', 'SO: Windows XP SP3, Windows XP SP2 de 64 bits, Windows Vista SP2 (32 ou 64 bits) ou Windows 7 (32 ou 64 bits). (Não suportado - Windows 95, Windows 98, Windows ME, Windows NT 4.0 e Windows 2000 não são suportados.) Processador: Intel Core 2 Duo 2.0 GHZ ou AMD Athlon X2 64 2.4GHZ; 1,5 GB Windows® XP / 2 GB Windows Vista® - Windows 7® Memory: 1GB (XP), 1.5GB (Vista), 1.5 GB (Windows 7) Espaço no Disco Rígido: 8 GB de espaço livre no disco rígido. Espaço adicional necessário para a instalação do DirectX 9.0c e para jogos salvos Placa de Vídeo: Compatível com DirectX® 9.0c Placa de vídeo de 256 MB com aceleração 3D com Shader Model 3.0 * ou superior Placa de som: Placa de som compatível com DirectX 9.0c DVD-ROM: Unidade de DVD-ROM com velocidade de 8X (somente usuários de disco) Jogabilidade online: conexão de banda larga para ativação online e jogabilidade online - 512 Kbps ou mais rápido Direct X®: DirectX 9.0c', 'R$ 29,99 ', 'https://store.steampowered.com/app/47870/Need_For_Speed_Hot_Pursuit/', '5de852ceede1d.jpg', '5de852ceede2a.jpg', '5de852ceede31.jpg'),
(13, 'Outlast 2', 'Terror', 'Outlast 2 traz-te Sullivan Knoth e os seus seguidores, que abandonaram o nosso mundo cruel para fundar Temple Gate, uma cidade situada nas profundezas do deserto, longe da civilização. Knoth e o seu rebanho estão a preparar-se para as adversidades do fim dos tempos, e tu estás no centro do furacão. Tu és Blake Langermann, um operador de câmara que trabalha com a sua esposa, Lynn. Sois ambos jornalistas de investigação, dispostos a correr riscos e ir até ao fundo para descobrir as histórias que mais ninguém se atreveria a investigar.', 'MÍNIMOS: SO: Windows Vista / 7 / 8 / 10, 64-bits Processador: Intel Core i3-530 Memória: 4 GB de RAM Placa de vídeo: 1GB VRAM, NVIDIA Geforce GTX 260 / ATI Radeon HD 4870 DirectX: Versão 10 Armazenamento: 30 GB de espaço disponível Placa de som: DirectX Compatible Outras observações: Targetting 720p @ 30 fps  RECOMENDADOS: SO: Windows Vista / 7 / 8 / 10, 64-bits Processador: Intel Core i5 Memória: 8 GB de RAM Placa de vídeo: 1.5GB VRAM, NVIDIA Geforce GTX 660 / ATI Radeon HD 7850 DirectX: Versão 11 Armazenamento: 30 GB de espaço disponível Placa de som: DirectX Compatible Outras observações: Targetting 1080p @ 60 fps', 'R$ 57,99', 'https://store.steampowered.com/app/414700/Outlast_2/', '5de85348a7a25.jpg', '5de85348a7a32.jpg', '5de85348a7a3a.jpg'),
(14, 'Rocket League®', 'Esportes', 'Um jogo de ação automobilística futurista, Rocket League®, permite que os jogadores dirijam veículos turbinados que acertam bolas para marcarem gols incríveis e realizarem defesas épicas em arenas variadas e altamente detalhadas. Usando um sistema de física avançado para simular interações realistas, Rocket League® usa massa e momento para dar aos jogadores uma sensação completa de controle intuitivo nesta incrível e criativa abordagem de futebol de alta octanagem.', 'MÍNIMOS: SO: Windows 7 or Newer Processador: 2.4 GHz Dual core Memória: 2 GB de RAM Placa de vídeo: NVIDIA GTX 260 or ATI 4850 DirectX: Versão 9.0c Rede: Conexão de internet banda larga Armazenamento: 7 GB de espaço disponível  RECOMENDADOS: SO: Windows 7 or Newer Processador: 2.5+ GHz Quad core Memória: 4 GB de RAM Placa de vídeo: NVIDIA GTX 660 or better, ATI 7950 or better DirectX: Versão 9.0c Rede: Conexão de internet banda larga Armazenamento: 7 GB de espaço disponível Outras observações: Gamepad or Controller Recommended', 'R$ 36,99', ' https://store.steampowered.com/app/252950/Rocket_League/', '5de853a37d17b.jpg', '5de853a37d184.jpg', '5de853a37d18a.jpg'),
(15, 'Rust', 'Indie', 'O único objetivo em Rust é sobreviver. Para fazer isso, você precisará superar lutas como fome, sede e frio. Acenda uma fogueira. Construir um abrigo. Mate animais por carne. Proteja-se de outros jogadores e mate-os por carne. Crie alianças com outros jogadores e forme uma cidade. Faça o que for preciso para sobreviver.', 'MÍNIMOS: Requer um processador e sistema operacional de 64 bits SO: Windows 7 64bit Processador: Intel Core i7-3770 / AMD FX-9590 or better Memória: 8 GB de RAM Placa de vídeo: GTX 670 2GB / AMD R9 280 better DirectX: Versão 11 Rede: Conexão de internet banda larga Armazenamento: 20 GB de espaço disponível  RECOMENDADOS: Requer um processador e sistema operacional de 64 bits SO: Windows 10 64bit Processador: Intel Core i7-4690K / AMD Ryzen 5 1600 Memória: 16 GB de RAM Placa de vídeo: GTX 980 / AMD R9 Fury DirectX: Versão 12 Rede: Conexão de internet banda larga Armazenamento: 20 GB de espaço disponível', 'R$ 65,99', 'https://store.steampowered.com/app/252490/Rust/', 'rust.png', 'rust1.jpg', 'rust2.jpg'),
(16, 'The Elder Scrolls V: Skyrim Special Edition', 'RPG', 'Vencedora de mais de 200 prêmios de Jogo do Ano, Skyrim Special Edition dá vida à fantasia épica em detalhes impressionantes. A edição especial inclui o jogo aclamado pela crítica e complementos com recursos totalmente novos, como arte e efeitos remasterizados, raios divinos volumétricos, profundidade de campo dinâmica, reflexos no espaço da tela e muito mais. Skyrim Special Edition também traz todo o poder dos mods para o PC e consoles. Novas quests, ambientes, personagens, diálogos, armaduras, armas e muito mais - com Mods, não há limites para o que você pode experimentar.', 'Mínimo: SO: Windows 7 / 8.1 / 10 (versão de 64 bits) Processador: Intel i5-750/AMD Phenom II X4-945 Memória: 8 GB de RAM Placa de vídeo: NVIDIA GTX 470 1GB /AMD HD 7870 2GB Armazenamento: 12 GB de espaço disponível', 'R$ 169,90', 'https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/', '5de8547889b0c.jpg', '5de8547889b16.jpg', '5de8547889b1d.jpg'),
(17, 'Tom Clancy’s Rainbow Six Siege', 'Estrategia', 'Domine a arte da destruição e do uso de gadgets em Tom Clancy’s Rainbow Six Siege. Enfrente combates intensos em curta distância, alta letalidade, decisões táticas, jogabilidade em equipe e ação explosiva a todo momento. Vivencie uma nova era de tiroteios ferozes e estratégia de alto nível nascida do grande legado dos jogos de Tom Clancy\'s Rainbow Six passados', 'MÍNIMOS: SO: Windows 7, Windows 8.1, Windows 10 (64bit versions required) Processador: Intel Core i3 560 @ 3.3 GHz or AMD Phenom II X4 945 @ 3.0 GHz Memória: 6 GB de RAM Placa de vídeo: NVIDIA GeForce GTX 460 or AMD Radeon HD 5870 (DirectX-11 compliant with 1GB of VRAM) Rede: Conexão de internet banda larga Armazenamento: 61 GB de espaço disponível Placa de som: DirectX® 9.0c compatible sound card with latest drivers  RECOMENDADOS: SO: Windows 7 SP1, Windows 8.1, Windows 10 (64bit versions required) Processador: Intel Core i5-2500K @ 3.3 GHz or better or AMD FX-8120 @ 3.1 Ghz or better Memória: 8 GB de RAM Placa de vídeo: NVIDIA GeForce GTX 670 (or GTX 760 / GTX 960) or AMD Radeon HD 7970 (or R9 280x [2GB VRAM] / R9 380 / Fury X) Rede: Conexão de internet banda larga Armazenamento: 61 GB de espaço disponível Placa de som: DirectX® 9.0c compatible sound card 5.1 with latest drivers', 'R$59.99', 'https://store.steampowered.com/app/359550/Tom_Clancys_Rainbow_Six_Siege/?curator_clanid=27270161', '5de854ce5acd6.jpg', '5de854ce5acdf.jpg', '5de854ce5ace5.jpg');

-- --------------------------------------------------------

--
-- Estrutura da tabela `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(10) NOT NULL,
  `nome` varchar(220) NOT NULL,
  `email` varchar(220) NOT NULL,
  `usuario` varchar(220) NOT NULL,
  `senha` varchar(220) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `usuarios`
--

INSERT INTO `usuarios` (`id`, `nome`, `email`, `usuario`, `senha`) VALUES
(1, 'igor', 'igorluis0107@gmail.com', 'igor', '25f9e794323b453885f5181f1b624d0b'),
(9, 'ADM1', 'ADM1@gmail.com', 'ADM KJJJ', '202cb962ac59075b964b07152d234b70');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `jogos`
--
ALTER TABLE `jogos`
  ADD PRIMARY KEY (`id`);

--
-- Índices para tabela `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `jogos`
--
ALTER TABLE `jogos`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT de tabela `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
